name: Maven - Quality Assurance

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string

concurrency:
  group: pr-develop-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  hadolint:
    uses: ./.github/workflows/wfc-hadolint.yaml
    with:
      runner: ${{ inputs.runner }}
      containerfile-path: "Dockerfile"
      comment-recreate: true
  build:
    uses: ./.github/workflows/maven-build.yaml
    with:
      runner: ${{ inputs.runner }}
      version-suffix: "-pr-${{ github.event.pull_request.number }}"
      containerfile-path: "Dockerfile"
      push: false
      analyze: false
    secrets: inherit