name: Maven - Create Snapshot

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      bumping-message:
        required: false
        type: string
        default: "Bump incremental version"

concurrency:
  group: develop
  cancel-in-progress: false

jobs:
  bump-version:
    runs-on: ${{ inputs.runner }}
    container:
      image: docksdtr.indra.es/piarq-21.devo/sdops-dope-tools/maven:gh-runner-pr-23-2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: Bump version
        run: |
          mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit -DprocessAllModules
      - name: Push changes
        uses: enagas-gitops/enagas-dope-github-actions-libraries/utils/push@main
        with:
          user: sdops-app
          app-id: 904133
          commit-changes: true
          commit-message: ${{ inputs.bumping-message }}
          private-key: ${{ secrets.GH_PRIVATE_KEY }}
  build:
    uses: ./.github/workflows/maven-build.yaml
    with:
      runner: ${{ inputs.runner }}
      version-suffix: "-SNAPSHOT"
      containerfile-path: "Dockerfile"
      push: true
      analyze: false
    secrets: inherit
  deploy:
    name: Deploy
    needs:
      - build
    uses: ./.github/workflows/wfc-helm-config.yaml
    with:
      runner: ${{ inputs.runner }}
      environment: dev
      version: ${{ needs.build.outputs.tag }}
    secrets: inherit
