name: NPM - Create Snapshot

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      bumping-message:
        required: false
        type: string
        default: "Bump incremental version"

concurrency:
  group: develop
  cancel-in-progress: false

jobs:
  bump-version:
    runs-on: ${{ inputs.runner }}
    container:
      image: docksdtr.indra.es/piarq-21.devo/sdops-dope-tools/maven:gh-runner-pr-23-2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: Get app version
        id: version
        run: |
          version=$(cat package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[",]//g')
          version=$(echo $version | xargs) # remove leading and trailing whitespaces
          echo "Current version: $version"
          next_version=$(echo $version | awk -F. '{print $1"."$2"."$3+1}')
          echo "Next version: $next_version"
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "next_version=$next_version" >> $GITHUB_OUTPUT
      - name: Bump version
        run: |
          version=${{ steps.version.outputs.version }}
          next_version=${{ steps.version.outputs.next_version }}
          echo "Bumping version from $version to $next_version"
          # sed -i "s/\"version\": \"$version\"/\"version\": \"$next_version\"/" package.json
          sed -i "0,/\"version\": \"$version\"/s//\"version\": \"$next_version\"/" package.json
      - name: Push changes
        uses: enagas-gitops/enagas-dope-github-actions-libraries/utils/push@main
        with:
          user: sdops-app
          app-id: 904133
          commit-changes: true
          commit-message: ${{ inputs.bumping-message }}
          private-key: ${{ secrets.GH_PRIVATE_KEY }}
  build:
    uses: ./.github/workflows/npm-build.yaml
    with:
      runner: ${{ inputs.runner }}
      version-suffix: "-SNAPSHOT"
      env: dev
      base-url: ${{ vars.BASE_URL_DEV }}
      rest-api-url: ${{ vars.REST_API_URL_DEV }}
      containerfile-path: "Dockerfile"
      push: true
      analyze: false
    secrets: inherit
  deploy:
    name: Deploy
    needs:
      - build
    uses: ./.github/workflows/wfc-helm-config.yaml
    with:
      runner: ${{ inputs.runner }}
      environment: dev
      version: ${{ needs.build.outputs.tag }}
    secrets: inherit
